### ISSUE TITLE
Get random credentials in a single request

### ISSUE THREAD

**Issue by matlink** [yeriomin/token-dispenser#10]
Would it be possible to add a way, like /email, to get a token from a random configured account?
For example, if I have configured 
```
gplaycliacc@gmail.com password
gplaycliacce@gmail.com password
```
in my passwords.txt, the path /email/random would use one of the two.
This thing is already possible, by calling /email and using it, however it requires 2 requests.
I could write a PR if you need so.

**Comment by yeriomin** [comment]
I tried it and it does not really speed things up, since the requests to Google are still made the same way.

Also it would make it imposible to return tokens plainly. Some response wrapper/format would need to be added (like JSON) which would make the responses a lot less intuitive than now.
