### ISSUE TITLE
Not able to generate authentication token

### ISSUE THREAD

**Issue by zhang-li** [yeriomin/token-dispenser#11]
After I runt the "java -jar target/token-dispenser.jar" command, what I get is just "Not Found" in the web page at http://localhost:8080/token/email/app01011881@gmail.com. 
May I know what is the possible reason?

Here is my config.properties file:
spark-host=0.0.0.0
spark-port=8080
storage=plaintext
storage-plaintext-path=passwords.txt
enable-email-retrieval=false

Thanks in advance for any suggestion.

**Comment by yeriomin** [comment]
Check the logs. Make sure `passwords.txt` is readable. Since `plaintext` was not default at the moment you wrote the issue, make sure the config in your `target/token-dispenser.jar` is the one you want.
