### ISSUE TITLE
Auth error on CircleCI

### ISSUE THREAD

**Issue by peterstory** [yeriomin/token-dispenser#12]
When I use the token-dispenser on my laptop, I'm able to get a token, and I can use it to download APKs. However, I try to get a token with the same settings, but running on [CircleCI](https://circleci.com), I get the following exception:

https://github.com/yeriomin/token-dispenser/blob/2bb08d97c36b0f806940397d6cc683f468f79aec/src/main/java/com/github/yeriomin/tokendispenser/OkHttpClientAdapter.java#L118-L119

Can you think of a reason why this might be the case? Have you ever experienced Google rate limiting tokens? 

EDIT: To be more specific, I'm using ae40bc47b408363a70d65a10909c9154799fb79a.

**Comment by yeriomin** [comment]
> Can you think of a reason why this might be the case?

No. Some configuration issue maybe? `AuthException` means the request was made but the login-password pair was incorrect.

> Have you ever experienced Google rate limiting tokens?

No. Since the tokens are long lived, there is no need to generate tokens more than once per device.

Why would you run it on circleci? Are you adding tests? It would be a bad idea to test on a live API. For test purposes I've [recorded some requests from live API](https://github.com/yeriomin/play-store-api/tree/master/src/test/resources).

**Comment by peterstory** [comment]
> Why would you run it on circleci? Are you adding tests? It would be a bad idea to test on a live API. For test purposes I've recorded some requests from live API.

As part of our CI tests, we test downloading the latest versions of popular Android apps. I think the problem is just an artifact of CircleCI not working well: other network-dependent tests of ours also fail occasionally. So I think it's safe to say that this isn't a problem with your code.

**Comment by peterstory** [comment]
> No. Since the tokens are long lived, there is no need to generate tokens more than once per device.

How long are the tokens valid for? A few days? Months?

**Comment by yeriomin** [comment]
Months. In fact I have never seen it become invalid over time.

**Comment by peterstory** [comment]
Wow, very good to know! In that case, I'll try caching the token for CI.

**Comment by matlink** [comment]
Are you talking about AuthSubToken? In fact, I find it to last for a few minutes. Has it changed recently?

**Comment by yeriomin** [comment]
@matlink On Oct 10 it still lasted for quite a lot. I wrote this just a couple of days before it changed.
