### ISSUE TITLE
how to obtain tokens

### ISSUE THREAD

**Issue by korangu** [yeriomin/token-dispenser#18]
can you show me some sample http requests how the tokens are obtained from username and password?
so i can try on my preferred language?

**Comment by yeriomin** [comment]
token-dispenser is just a wrapper around [play-store-api](https://github.com/yeriomin/play-store-api) library.

The requests are constructed here: https://github.com/yeriomin/play-store-api/blob/2bb7b4af3162969622cb21ec64093195be0853bf/src/main/java/com/github/yeriomin/playstoreapi/GooglePlayAPI.java#L283

You get a token by making a GET request with email, encrypted password and some other headers to https://android.clients.google.com/auth. It returns several key-value pairs in plaintext, one of which contains the token.
