### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by matlink** [yeriomin/token-dispenser#2]
Sometimes, https://matlink.fr/token/email/gplaycliacc@gmail.com returns 'Auth error' probably due to too many requests with the same account.
Are you aware?

**Comment by yeriomin** [comment]
Auth errors should no longer happen with version 0.2.

**Comment by matlink** [comment]
Hum, since today, token-dispenser throws auth error at every request with different accounts. We should re-open.

**Comment by yeriomin** [comment]
@matlink I checked my deployment and it works. Try changing the password.

**Comment by matlink** [comment]
Yes, my bad, google might have blocked these accounts 
-- 
Matlink
