### ISSUE TITLE
Mongodb official docker image auth error

### ISSUE THREAD

**Issue by NoMore201** [yeriomin/token-dispenser#5]
Using the official [mongodb docker image](https://hub.docker.com/_/mongo/), this app will give auth error even if all the credentials are saved correctly  into mongodb (verified multiple times).

I found a workaround [here](https://stackoverflow.com/questions/29006887/mongodb-cr-authentication-failed) but i'm not sure what these commands do, or if it is a secure approach, it just works after typing those command into mongo interactive shell.

Maybe you could just mention this in the readme.

PS. I made [dockerfiles](https://github.com/NoMore201/docker-token-dispenser/tree/master/backend-mongodb) for your project, maybe they can be useful to someone

**Comment by yeriomin** [comment]
The docker image you are using is too *new*.

My instance of token dispenser is running on openshift 2, and mongodb version is v2.6 there. See pom.xml.

Thanks for the docker files, I'll use them as reference and update mongo client dependency.

**Comment by yeriomin** [comment]
Added a Dockerfile and pushed an image to docker hub: `yeriomin/play-store-token-dispenser:0.2`. Also tested the image with openshift 3. `plaintext` storage is used.
