### ISSUE TITLE
Whenever I am trying to do mvn install, I am getting this error. Can you please help?

### ISSUE THREAD

**Issue by avinashkmr632** [yeriomin/token-dispenser#6]
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.072 s
[INFO] Finished at: 2017-07-14T17:42:13+05:30
[INFO] Final Memory: 6M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/avinash.af.kumar/Desktop/apache-maven-3.2.2/bin). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by yeriomin** [comment]
>The goal you specified requires a project to execute but there is no POM in this directory (/Users/avinash.af.kumar/Desktop/apache-maven-3.2.2/bin). Please verify you invoked Maven from the correct directory.

Did you do what is tells you to do?

**Comment by avinashkmr632** [comment]
Thank you. The issue was resolved.
