### ISSUE TITLE
'Malformed request' for some google accounts

### ISSUE THREAD

**Issue by kttkyk** [yeriomin/token-dispenser#8]
For some accounts I am able to receive the authentication token.
However some of the accounts, I receive 'Malformed request' instead.

I was able to login with these accounts using the browser.

Is there some reason for this?

**Comment by yeriomin** [comment]
Try using those accounts to log in to Play Store on a real device. Once should be enough.

**Comment by kttkyk** [comment]
Works fine now.
Thank you.
